### ISSUE TITLE
現在地を取得して天気を取得

### ISSUE THREAD

**Issue by yosse95ai** [yosse95ai/my-app#10]
# Description
Add the function to retrieve the current position.

Add the function to get the weather from the current location on the first timing.

In [issue/10](https://github.com/yosse95ai/my-app/tree/issue/10) branch.

# Tasks
- [x] Get current position
- [ ] Get the weather from you current position
- [ ] View the weather from current position

**Comment by yosse95ai** [comment]
飽きました
