### ISSUE TITLE
天気を検索すると現在時刻から48時間分の気温グラフを出す

### ISSUE THREAD

**Issue by yosse95ai** [yosse95ai/my-app#4]
# Description
Added the function to output temperature graph from 0:00 a.m. to 23:00 p.m. using the result of the search form.

In [`issue/4`](https://github.com/yosse95ai/my-app/tree/issue/4) branch.

# Tasks
- [x] Install `chart.js`, `ng2-charts`
- [x] Add `daily-temp-chart-componenet`
- [x] I/O search results and output graph

**Comment by yosse95ai** [comment]
d3ではうまくいきそうになかったので、`chart.js`と`ng2-charts`を使用する。

**Comment by yosse95ai** [comment]
OneCallAPIで取得できるデータが48時間分あり、前の時間に戻る必要性をあまり感じなかったので、
現在時刻から48時間分のデータを表示する方針に変更。

**非同期周りでグラフの再描画が行われない問題が発生中！**

[解決方法！](https://ja.stackoverflow.com/questions/78438/angular12%e3%81%a7ng2-charts%e3%81%ae%e3%83%81%e3%83%a3%e3%83%bc%e3%83%88%e5%86%8d%e6%9b%b4%e6%96%b0%e3%81%8c%e8%a1%8c%e3%82%8f%e3%82%8c%e3%81%aa%e3%81%84)
